# CMake generated Testfile for 
# Source directory: /workspace/tests
# Build directory: /workspace/build_quality/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_init "/workspace/build_quality/tests/test_init")
set_tests_properties(test_init PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;22;add_test;/workspace/tests/CMakeLists.txt;26;add_iolink_test;/workspace/tests/CMakeLists.txt;0;")
add_test(test_crc "/workspace/build_quality/tests/test_crc")
set_tests_properties(test_crc PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;22;add_test;/workspace/tests/CMakeLists.txt;27;add_iolink_test;/workspace/tests/CMakeLists.txt;0;")
add_test(test_dll "/workspace/build_quality/tests/test_dll")
set_tests_properties(test_dll PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;22;add_test;/workspace/tests/CMakeLists.txt;28;add_iolink_test;/workspace/tests/CMakeLists.txt;0;")
add_test(test_pd "/workspace/build_quality/tests/test_pd")
set_tests_properties(test_pd PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;22;add_test;/workspace/tests/CMakeLists.txt;29;add_iolink_test;/workspace/tests/CMakeLists.txt;0;")
add_test(test_isdu "/workspace/build_quality/tests/test_isdu")
set_tests_properties(test_isdu PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;22;add_test;/workspace/tests/CMakeLists.txt;30;add_iolink_test;/workspace/tests/CMakeLists.txt;0;")
add_test(test_isdu_segmented "/workspace/build_quality/tests/test_isdu_segmented")
set_tests_properties(test_isdu_segmented PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;22;add_test;/workspace/tests/CMakeLists.txt;31;add_iolink_test;/workspace/tests/CMakeLists.txt;0;")
add_test(test_events "/workspace/build_quality/tests/test_events")
set_tests_properties(test_events PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;22;add_test;/workspace/tests/CMakeLists.txt;32;add_iolink_test;/workspace/tests/CMakeLists.txt;0;")
add_test(test_ds "/workspace/build_quality/tests/test_ds")
set_tests_properties(test_ds PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;22;add_test;/workspace/tests/CMakeLists.txt;33;add_iolink_test;/workspace/tests/CMakeLists.txt;0;")
add_test(test_error_recovery "/workspace/build_quality/tests/test_error_recovery")
set_tests_properties(test_error_recovery PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;22;add_test;/workspace/tests/CMakeLists.txt;34;add_iolink_test;/workspace/tests/CMakeLists.txt;0;")
add_test(test_timing "/workspace/build_quality/tests/test_timing")
set_tests_properties(test_timing PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;22;add_test;/workspace/tests/CMakeLists.txt;35;add_iolink_test;/workspace/tests/CMakeLists.txt;0;")
add_test(test_integration_full "/workspace/build_quality/tests/test_integration_full")
set_tests_properties(test_integration_full PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;22;add_test;/workspace/tests/CMakeLists.txt;36;add_iolink_test;/workspace/tests/CMakeLists.txt;0;")
add_test(test_application "/workspace/build_quality/tests/test_application")
set_tests_properties(test_application PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;22;add_test;/workspace/tests/CMakeLists.txt;37;add_iolink_test;/workspace/tests/CMakeLists.txt;0;")
add_test(test_m_sequence_types "/workspace/build_quality/tests/test_m_sequence_types")
set_tests_properties(test_m_sequence_types PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;22;add_test;/workspace/tests/CMakeLists.txt;38;add_iolink_test;/workspace/tests/CMakeLists.txt;0;")
add_test(test_locking "/workspace/build_quality/tests/test_locking")
set_tests_properties(test_locking PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;22;add_test;/workspace/tests/CMakeLists.txt;41;add_iolink_test;/workspace/tests/CMakeLists.txt;0;")
add_test(test_config "/workspace/build_quality/tests/test_config")
set_tests_properties(test_config PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;22;add_test;/workspace/tests/CMakeLists.txt;42;add_iolink_test;/workspace/tests/CMakeLists.txt;0;")
add_test(test_pd_variable "/workspace/build_quality/tests/test_pd_variable")
set_tests_properties(test_pd_variable PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;22;add_test;/workspace/tests/CMakeLists.txt;43;add_iolink_test;/workspace/tests/CMakeLists.txt;0;")
add_test(test_baudrate "/workspace/build_quality/tests/test_baudrate")
set_tests_properties(test_baudrate PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;22;add_test;/workspace/tests/CMakeLists.txt;44;add_iolink_test;/workspace/tests/CMakeLists.txt;0;")
